### ISSUE TITLE
Webpack config / externals

### ISSUE THREAD

**Issue by pjatx** [Pixel2HTML/Pixel2HTML#4]
Refactoring an old project I made with the previous version and running into a similar issue as this: https://github.com/Pixel2HTML/shopify-skeleton/issues/4

Wondering if it's possible to define externals here but can't find a webpack config anywhere. 

Do you still recommend to handle this by adding the vendors to the `scriptVendors: ` array? 

Thanks!

**Comment by shelldandy** [comment]
We now use this hand-crafted way of sharing our webpack config which of course is extendable:

https://github.com/Pixel2HTML/Pixel2HTML/blob/master/packages/scripts-frontend/readme.md#customizing-the-underlying-config

**Comment by pjatx** [comment]
Amazing - this is really cool. Thanks for open sourcing and being responsive!

**Comment by shelldandy** [comment]
Yaay glad it was useful, closing this ticket now
